#Intials
#Joshua Allen
#P4T1 - Lab part B
import turtle
t = turtle.pen()
turtle.forward(100)
turtle.backward(50)
turtle.right(90)
turtle.forward(150)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(25)
turtle.up()
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(25)
turtle.down()
turtle.right(180)
turtle.forward(150)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(150)
turtle.right(180)
turtle.forward(75)
turtle.right(-90)
turtle.forward(50)
turtle.up()
